### ISSUE TITLE
Issue in Installing PYSAP

### ISSUE THREAD

**Issue by vicky1004** [SecureAuthCorp/pysap#21]
when i try to install pysap for windows, getting the below error.
Using pip install pysap to install the module. 

Python Version: 3.6
Visual Studio:14.0

Error:
running develop
running egg_info
writing pysap.egg-info\PKG-INFO
writing dependency_links to pysap.egg-info\dependency_links.txt
writing requirements to pysap.egg-info\requires.txt
writing top-level names to pysap.egg-info\top_level.txt
reading manifest file 'pysap.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pysap.egg-info\SOURCES.txt'
running build_ext
building 'pysapcompress' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe /c /
nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Python36\include" "-IC:\Prog
ram Files\Python36\include" -Iinclude\10.0.10240.0\ucrt "-IC:\Program Files (x86
)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kit
s\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\
4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-I
C:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Wi
ndows Kits\8.1\include\winrt" /EHsc /Tppysapcompress/pysapcompress.cpp /Fobuild\
temp.win-amd64-3.6\Release\pysapcompress/pysapcompress.obj
pysapcompress.cpp
pysapcompress/pysapcompress.cpp(460): error C3861: 'Py_InitModule3': identifier
not found
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\
amd64_x86\\cl.exe' failed with exit status 2

**Comment by martingalloar** [comment]
Hey @vicky1004! pysap is currently only supported on Python 2. Can you switch there and try again?

Now that scapy is Python 3 compatible I've making pysap to support it as well in my todo list, but will require some effort and thus I don't currently have an ETA for it.

**Comment by vicky1004** [comment]
Thanks for your reply @martingalloar 

Yes able to install in python2.7. Do you have any work around for this issue to make work on python 3?

**Comment by martingalloar** [comment]
TBH, I created branch [python2-3](https://github.com/CoreSecurity/pysap/tree/python2-3) but only change there was to enable Python 3 in Travis. Surveyed the work that need to be done and I think the bigger effort after moving the `pysapcompress` C extension to Python 2/3 would be to make the examples to work on both versions using six. Any help there is appreciated!

**Comment by okuuva** [comment]
I actually started working on the Python3 compatibility last week on my fork, but was halted after I noticed that pysapcar script is currently broken and moved my effort on fixing that.

**Comment by okuuva** [comment]
@martingalloar as I stated previously, I've already started working on Python 3 compatibility. So far I've focused on SAPCAR, haven't started working on the C extension yet. Some questions:

* Should we track Python 3 compatibility here or on some other issue?
* Do you have some parts you'd like to port yourself?
  - If so how should we coordinate the porting effort?

**Comment by martingalloar** [comment]
Support for Python 3 will be tracked in https://github.com/CoreSecurity/pysap/projects/1, closing.
